---
title: Research
---

## Climate-smart spatial planning. 

Human threats – including fishing, climate change, habitat destruction, pollution, and invasive species – are leading to declining abundance of many marine species. To mitigate impacts of these threats on biodiversity, marine protected areas – national parks in the ocean – are being created. As there is a global push to increase the marine protected area network coverage from 8% to potentially 20% or even 30% in the next decade, developing the science to underpin where to place these reserves is critical and timely.

A current focus of our research is thus how to design robust climate-smart marine protected areas that conserve biodiversity, protect against climate change, retain biodiversity as the climate warms, ensure connectivity, minimise conflict with fishing, whilst considering the 3-D nature of the ocean. This is a tough task! It requires extensive computational expertise and infrastructure. Our work involves mapping global biodiversity and developing new approaches to the design of climate-smart marine protected area networks using state-of-the-art statistical and computational approaches on super-computers.

## Zooplankton size-spectra

Body size has been described as the ‘master trait’, setting the pace of life by dictating processes such as metabolism, respiration, development, movement, and constraining the role of an individual in its food web. In this project, we are collating thousands of observations of zooplankton size, from all over the world, in order to reveal ecological rates and processes not readily apparent from conventional taxonomic methods. This relationship between organism size and vital rates is strongest in plankton systems, where nutrient and light limitation, grazing encounters, and the efficiency of energy transfer between trophic levels are all size dependent

## Zooplankton Energy Transfer Efficiency

We are generating maps of broad taxonomic groups of zooplankton (Copepods, Chaetognaths, Euphausiids, Larvaceans, Salps, Jellyfish). These empirical data will be used in conjunction with a zooplankton-resolved size-spectra model in order to quantify the global energy transfer efficiency from phytoplankton to fish.